Yamilovs\PaymentBundle\Entity\Purchase:
    type: entity
    table: null
    repositoryClass: Yamilovs\PaymentBundle\Repository\PurchaseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        productType:
            type: integer
        productId:
            type: integer

    oneToMany:
        payments:
            targetEntity: Payment
            mappedBy: purchase

    lifecycleCallbacks: {  }
