services:
    sonata.admin.tour:
        class: ProfiTravel\PaymentBundle\Admin\PaymentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Платежи", label: "Список" }
        arguments:
            - ~
            - ProfiTravel\PaymentBundle\Entity\Payment
            - ~
        calls:
            - [ setTranslationDomain, [admin]]
            - [ setPayments, ["@payment.service.factory"]]
