services:
    sonata.admin.tour:
        class: Yamilovs\PaymentBundle\Admin\PaymentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Платежи", label: "Список" }
        arguments:
            - ~
            - Yamilovs\PaymentBundle\Entity\Payment
            - ~
        calls:
            - [ setTranslationDomain, [admin]]
            - [ setPayments, ["@yamilovs.payment.factory"]]
