services:
    yamilovs.payment.factory:
        class: Yamilovs\PaymentBundle\Manager\PaymentFactory
        arguments: ["%yamilovs_payment.services.default%"]

    yamilovs.payment.abstract:
        abstract: true
        calls:
            - [setLogger, ["@logger"]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: monolog.logger, channel: payment }

    yamilovs.payment.platron:
        class: Yamilovs\PaymentBundle\Manager\PaymentServicePlatron
        parent: yamilovs.payment.abstract
        public: false
        arguments:
            - "%yamilovs_payment.services.platron.hostname%"
            - "%yamilovs_payment.services.platron.merchant_id%"
            - "%yamilovs_payment.services.platron.secret_key%"
            - "%yamilovs_payment.services.platron.salt%"
            - "%yamilovs_payment.services.platron.api_url_init%"
        tags:
            - { name: YamilovsPaymentService }


    yamilovs.purchase:
        class: Yamilovs\PaymentBundle\Manager\PurchaseManager
        arguments: ["@doctrine.orm.entity_manager", "%yamilovs_payment.products%"]
